export {
  PLATFORM_FORMATS,
  PLATFORM_PROFILE_VERSION,
  PRODUCT_GEOMETRY_BASELINE,
  formatFor,
  formatsFor,
  type FormatKey,
  type Insets,
  type PlatformFormat,
  type Rect,
  type TypeSpec,
} from './profiles.js';
export {
  coverCrop,
  typeRegion,
  safeRect,
  safeZone,
  requiredMasterHeightPx,
  intersection,
  area,
  discCoverage,
  toDelivered,
  placeInSafeZone,
  type Focal,
  type Placement,
} from './geometry.js';
export {
  measure,
  measureAcrossPlatform,
  platformSafeZone,
  DEFAULT_THRESHOLDS,
  type AssetReading,
  type ViewportReading,
  type Thresholds,
  type MeasureInput,
  type LuminanceSampler,
} from './measure.js';
